title: "toapd2022 Blog"
description: "ドローン映像や防災無線などの活動報告"
author: "toapd2022"

baseurl: "/toapd2022"
url: "https://toapd2022.github.io"

timezone: "Asia/Tokyo"
permalink: /:year/:month/:day/:title/

# ← ここから追加
markdown: kramdown
kramdown:
  input: GFM
  parser: GFM
# ← ここまで

plugins:
  - jekyll-feed
  - jekyll-seo-tag
