title: "toapd2022 Blog"
description: "ドローン映像や防災無線などの活動報告"
author: "toapd2022"

baseurl: "/toapd2022"
url: "https://toapd2022.github.io"

timezone: "Asia/Tokyo"
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # ▼ もしGitHub Pagesで許可されていれば
  #   'jekyll-paginate' を追加（ただし現在は非推奨）
  - jekyll-paginate

# 1ページあたりの記事数
paginate: 5

# 2ページ目以降のURL例: /blog/page2, /blog/page3, ...
paginate_path: "/blog/page:num"
