name: Build and Deploy Jekyll site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Ruby をセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.7"

      - name: Bundler をインストール
        run: gem install bundler

      - name: 依存をインストール
        run: bundle install

      - name: Jekyll サイトをビルド
        run: bundle exec jekyll build --destination public

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
